name: UI testing

on:
  workflow_dispatch:
    inputs:
      chrome_131_0:
        description: 'Chrome (131.0)'
        required: false
        type: boolean

      firefox_133_0:
        description: 'Firefox (133.0)'
        required: false
        type: boolean

jobs:
  TestChrome_131_0:
    name: Test Chrome 131.0
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.chrome_131_0 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Install Chrome Browser
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Tests
        run: |
          export BROWSER=chrome
          mvn -q test

  TestFirefox_133_0:
    name: Test Firefox 133.0
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.firefox_133_0 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Install Firefox Browser
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Run Tests
        run: |
          export BROWSER=firefox
          mvn -q test
